name: Build and Test API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: mobile-api

jobs:
  build-and-test:
    name: Build and Test API
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint source files
        run: npm run lint

      - name: Build and start container
        run: docker compose -f docker-compose.dev.yml up -d

      - name: Sleep for 1 minute
        run: sleep 60

      - name: Ping container
        run: curl localhost:3000/ping

      - name: Create .env file
        run: cp sample.env .env

      - name: Run tests
        run: npm test
