name: Flutter CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "mobile-app/**"
      - ".github/**"
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  flutter_test:
    name: flutter test
    defaults:
      run:
        working-directory: ./mobile-app
    runs-on: ubuntu-latest

    steps:
      - name: Remove unused software
        working-directory: /
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          echo "Free space:"
          df -h /

      - name: Checkout files
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          gradle-version: 7.6.3

      - name: Setup Java 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: AVD cache
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33

      - name: Ceate AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Setup Flutter 3.22.x
        uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # v2
        with:
          flutter-version: "3.22.x"
          channel: "stable"
          cache: true
          cache-key: flutter-3.22.x
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Create .env file
        run: |
          echo "HASHNODE_PUBLICATION_ID=$HASHNODE_PUBLICATION_ID" > .env
          echo "ALGOLIAAPPID=$ALGOLIA_APP_ID" >> .env
          echo "ALGOLIAKEY=$ALGOLIA_KEY" >> .env
          echo "AUTH0_DOMAIN=$AUTH0_DOMAIN" >> .env
          echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> .env
        env:
          HASHNODE_PUBLICATION_ID: ${{ secrets.HASHNODE_PUBLICATION_ID }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_KEY: ${{ secrets.ALGOLIA_KEY }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}

      - name: Install packages
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests
        run: |
          cd test
          flutter test unit
          flutter test services

      - name: Run tests in emulator
        uses: reactivecircus/android-emulator-runner@62dbb605bba737720e10b196cb4220d374026a6d # v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: cd mobile-app && if adb shell pm list packages | grep -q org.freecodecamp; then adb uninstall org.freecodecamp; fi && dart integration_test_runner.dart

      - name: Upload screenshots
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: always()
        with:
          name: screenshots
          path: mobile-app/screenshots/
          if-no-files-found: error
          retention-days: 7
